### ISSUE TITLE
bump

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/faunus-feedstock#1] opened 2019-01-15 18:25 UTC
@conda-forge-admin please rerender

**Comment by mlund** [comment] 2019-01-16 06:51
I suspect I do this by running `conda smithy rerender` on my forge and submit a PR? The OSX build fails on travis despite it passing in the staged recipe. The error is caused by a failing test that I sometimes observe for specific compiler and MPI combinations (docopt/docopt.cpp#106).

**Comment by mlund** [comment] 2019-01-16 07:05
Ahh, I see that your comment triggered the rerender service. Still unsure how to fix the osx build.

**Comment by mariusvniekerk** [comment] 2019-01-16 12:30
Id open a pr on a fork of yours adding a space somewhere, then you have a space to iterate.  You've basically hit the exact point where you are the first recipe to be rendered post compiler migration

**Comment by mlund** [comment] 2019-01-18 06:51
Thanks, all checks pass and I have merged. 2 of 4 of the post-merge OSX build matrix fails to upload to anaconda, though. The builds appear otherwise sound.

[![OSX](https://img.shields.io/travis/conda-forge/faunus-feedstock/master.svg?label=macOS)](https://travis-ci.org/conda-forge/faunus-feedstock)

**Comment by mariusvniekerk** [comment] 2019-01-18 13:53
Yeah you can just restart those.  Seems you hit some flakiness for the upload

**Closed as completed** 2019-01-21 18:45 UTC
